### ISSUE TITLE
Incorrect Port in README (localhost:6080 vs. localhost:80)

### ISSUE THREAD

**Issue by nanlour** [swen90006-2024/assignment-2-release#1]
Current Documentation:

> Once fuzzing is complete, the script will generate a plot showing the code coverage improvement over time, stored in plot.pdf. You can copy this file to your host computer, or you can view it directly from the container by typing localhost:6080 in your web browser, open a web browser or a PDF reader from the container, and then open the PDF file from there.

I can't figure out where port 6080 comes from; maybe it should be 80.

**Comment by Lanthian** [comment]
I know this probably isn't helpful to hear, but localhost:6080 worked fine for me.
